[package]
name = "nonphysical_cuda_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
nonphysical_core = {path="../nonphysical_core", features=["std"]}
nonphysical_std = {path="../nonphysical_std"}
nonphysical_cuda = {path="../nonphysical_cuda"}
nonphysical_ptx = {path="../nonphysical_ptx"}