[workspace]
resolver = "2"

members = [
    "nonphysical_core", "nonphysical_cuda",
    "nonphysical_ptx", "nonphysical_std", 
    "nonphysical_cuda_tests", "nonphysical_tests"
]

[profile.release]
codegen-units = 1
panic = "abort"
strip = true

[profile.lto]
inherits = "release"
lto="fat"
